<!DOCTYPE html>
<html>
<head>
    <?= $this->partial('user/auth/oauth2/header'); ?>
    <title>OAuth2 Authorization Request</title>
    <style>html,body{height:100%;}</style>
</head>
<body>
    <div class="d-flex flex-row justify-content-center align-items-center" style="height:100%;">
        <div class="card" style="max-width:500px;min-width:300px;margin:0 20px">
            <div class="card-body">
                <h5 class="card-title">Authorization Request</h5>
                <p class="card-text">
                    <strong><?= $app->name ?></strong> would like to use your information in
                    accordance with their respective terms of service and privacy policy.
                </p>

                <?php if($scopes): ?>
                    <p>The application would be able to:</p>
                    <ol>
                        <?php foreach($scopes as $scope): ?>
                            <li><?= $scope->about ?></li>
                        <?php endforeach; ?>
                    </ol>
                <?php endif; ?>

                <form method="POST" class="text-right">
                    <input type="hidden" name="allow" value="1">
                    <a href="<?= $cancel ?>" class="btn btn-default">Deny</a>
                    <button class="btn btn-primary">Allow</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>